### ISSUE TITLE
It is possible exports the angles of the arms?

### ISSUE THREAD

**Issue by b4zz4** [arnaud-ramey/easy_mocap#1]

**Comment by b4zz4** [comment]
OrientationFinder.cpp

    cout << endl << torso->center.x << endl;
    cout << torso->center.y << endl;
    cout << endl << body->arm_left()->angle << endl;
    cout << body->forearm_left()->angle << endl;
    cout << body->arm_right()->angle << endl;
    cout << body->forearm_right()->angle << endl;
    cout << body->shin_left()->angle << endl;
    cout << body->leg_left()->angle << endl;
    cout << body->shin_right()->angle << endl;
    cout << body->leg_right()->angle << endl;

**Comment by arnaud-ramey** [comment]
Nice to see you found the way! :)
